spring:
  profiles:
    active: development

---
# Development Profile (Local development)
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:h2:mem:university_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

---
# Production Profile (Docker deployment)
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://database:3306/university_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: university_user
    password: password123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

---
# Server Configuration
server:
  port: 8080